### ISSUE TITLE
Error 'budget limit must be larger than 0' even when specified

### ISSUE THREAD

**Issue by rcoundon** [DataChefHQ/cost-monitoring-construct#13]
I'm seeing the following error when trying to create the construct (1.0.4) from within an SST application:
```
Unable to create/update budget - budget limit must be larger than 0 
```

This is the code that I'm using:
```ts
createCostMonitoring(stack: Stack) {
    const costMonitoring = new ApplicationCostMonitoring(stack, {
      subscribers: ['someone@test.com'],
      monthlyLimitInDollars: 10,
      applicationName: 'some-name',
      defaultTopic: 'cost-monitoring',
    });
    costMonitoring.monitor();
  }
```

Is there anything obvious I'm doing wrong?

**Comment by rcoundon** [comment]
Looking at the generated output it seems the value isn't being passed through to Cloudformation:

```json
"applicationsomenamedevdaily080applicationsomenamedaily080budgetB41D3327": {
   "Type": "AWS::Budgets::Budget",
   "Properties": {
    "Budget": {
     "BudgetLimit": {
      "Amount": 0,
      "Unit": "USD"
     },
     "BudgetName": "application_somename_daily_0_%80_budget",
     "BudgetType": "COST",
     "CostFilters": {
      "TagKeyValue": [
       "user:cm:application$somename"
      ]
     },
     "TimeUnit": "DAILY"
    },
    "NotificationsWithSubscribers": [
     {
      "Notification": {
       "ComparisonOperator": "GREATER_THAN",
       "NotificationType": "ACTUAL",
       "Threshold": 80,
       "ThresholdType": "PERCENTAGE"
      },
      "Subscribers": [
       {
        "Address": {
         "Ref": "costmonitoringtopic1C6948DE"
        },
        "SubscriptionType": "SNS"
       }
      ]
     }
    ]
   }
  },
```

**Comment by kkiani** [comment]
@rcoundon, thanks for reporting the issue. This happens because ApplicationCostMonitoring creates an alert budget by dividing the monthly budget by 30. As you provide the value of 10 for your monthly budget and the budget value must be an integer value, the daily budget will be estimated as zero.

The class should throw an error if you provide a budget of less than $30, but it does not do that right now.

**Comment by rcoundon** [comment]
I see - thanks for getting back to me so quickly. I'm just experimenting at the moment, I'll try a higher budget in the meantime.

**Comment by kkiani** [comment]
@rcoundon you are welcome. You can open new issues if have any other problem.

ps: The pull request for fixing this issue is available [here](https://github.com/DataChefHQ/cost-monitoring-construct/pull/14).
